#!/bin/sh
#param list:
#$1 package name
#$2 deploy path
#$3 app name
function deploy()
{
	tar -xzf /tmp/$1 -C $2

	cd $2/$3

	#install bundle
	gem install bundle

	#install gems
	bundle install --local

	#db migrate
	rake db:migrate

	#relauch
	rails server -d	
}
