# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "selectors"))

Given /^"([^"]*)" registed in Keepin with email "([^"]*)" and password "([^"]*)"$/ do |username, email, password|
  user = User.new(:email => email, :password => "123456",:password_confirmation => "123456", :crypted_password=>"a7944c46edb15a444ee1facd57fb23cf7d675bf3634e0bd5728d9866bbd8f5154829981e0af0c5b50e2f5534484d8a398363fcd185c3737844e424dd81196907")
  user.save_without_session_maintenance
end

When /^"([^"]*)" post a word "([^"]*)" to the API with password "([^"]*)"$/ do |email, word, password|
  user = User.find_by_email(email)
  path = "/users/#{user.id}/words.json"
  authorize(user.email, password)
  data = { "user_id" => user.id, "word" => { "word" => word } }.to_json
  header 'Accept',       'application/json'
  header 'Content-Type', 'application/json'
  post path, data
end

Then /^Rick can get a response with HTTP status code (\d+) \(Created\)$/ do |code_wanted|
  last_response.status.should == code_wanted.to_i
end

Then /^the JSON response should be an array having a "([^"]*)" element with content "([^"]*)"$/ do |name, content|
  page = JSON.parse(last_response.body)
  page["word"][name].should == content
end
