# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a 
# newer version of cucumber-rails. Consider adding your own code to a new file 
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'curb'
require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "selectors"))

Given /^"([^"]*)" registed in Keepin with email "([^"]*)" and password "([^"]*)"$/ do |username, email, password|
  return if User.find_by_email(email)
  user = User.create(:name => username, :email => email, :password => password)
end

When /^"([^"]*)" post a word "([^"]*)" to the API with password "([^"]*)"$/ do |username, word, password|
  user = User.find_by_name(username)
  path = "/users/#{user.id}/words.json"
  data = { "user_id" => user.id, "word" => { "word" => word } }.to_json
  header 'Accept', 'application/json'
  header 'Content-Type', 'application/json'
  post path, data
end

Then /^Rick can get a response with HTTP status code (\d+) \(Created\)$/ do |code_wanted|
  last_response.status.should == code_wanted
end