# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a 
# newer version of cucumber-rails. Consider adding your own code to a new file 
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.


require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "selectors"))

# Commonly used webrat steps
# http://github.com/brynary/webrat

#  Given "Rick" registed in Keepin
Given /^"(.)*" registed in Keepin$/ do |username|
  @users = User.find_by_name(username)
end

# When "Lee" want to subscribe "Rick"'s words
When /^"(.*)" want to subscribe "(.*)"'s words$/ do |subscriber, username|
  #....
end